---
kind: DataManagerJobDefinition
kind-version: '2021.1'
name: Hello World
collection: cedric-test

jobs:
  hello-world:
    name: Hello World
    description: >-
      Simple python script that writes a prompt (eg "Hello World!") into a .txt file
    version: '1.0.0'
    category: test
    keywords:
    - test
    image:
      name: kgr26424/squonk-test
      tag: 'test'
      project-directory: /test
      working-directory: /test
      fix-permissions: false
    command: >-
      python -m hello_world --input '{{ inputPrompt }}'
      --output '{{ outputFile }}'
      {% if encoding is defined %}--encoding {{ encoding }}{% endif %}
    variables:
      order:
        options:
        - inputPrompt
        - outputFile
        - encoding
      outputs:
        type: object
        properties:
          outputFile:
            title: Output file
            mime-types:
            - text/plain
            creates: '{{ outputFile }}'
            type: file
      options:
        type: object
        required:
        - inputPrompt
        - outputFile
        properties:
          inputPrompt:
            title: Prompt to write into the output file (default Hello World).
            type: string
            default: "Hello World!"
          outputFile:
            title: Output file name (default prompt.txt)
            type: string
            pattern: "^[A-Za-z0-9_/\\.\\-]+$"
            default: prompt.txt
          encoding:
            title: Encoding (default utf-8)
            type: string
            enum:
            - utf-8
            - utf_16
            - utf_32
            - ascii
            - latin_1
            - mac_latin2
    tests:
      simple-execution:
        options:
          inputPrompt: "Hello World!"
          outputFile: prompt.txt
        checks:
          exitCode: 0
          outputs:
          - name: prompt.txt
            checks:
            - exists: true
            - lineCount: 1
      ascii-test:
        options:
          inputPrompt: "Hello World!"
          outputFile: prompt_ascii.txt
          encoding: ascii
        checks:
          exitCode: 0
          outputs:
          - name: prompt_ascii.txt
            checks:
            - exists: true
            - lineCount: 1
      latin1-test:
        options:
          inputPrompt: "Hello World!"
          outputFile: prompt_latin1.txt
          encoding: latin_1
        checks:
          exitCode: 0
          outputs:
          - name: prompt_latin1.txt
            checks:
            - exists: true
            - lineCount: 1
      maclatin2-test:
        options:
          inputPrompt: "Hello World!"
          outputFile: prompt_maclatin2.txt
          encoding: mac_latin2
        checks:
          exitCode: 0
          outputs:
          - name: prompt_maclatin2.txt
            checks:
            - exists: true
            - lineCount: 1
      multiplelines-test:
        options:
          inputPrompt: 'Line1\\nLine2\\nLine3\\nLine4\\nLine5'
          outputFile: prompt_5lines.txt
        checks:
          exitCode: 0
          outputs:
          - name: prompt_5lines.txt
            checks:
            - exists: true
            - lineCount: 5
